[2024-06-17T16:48:38.171-0400] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T16:48:38.193-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_data.extract_data manual__2024-06-17T20:48:32.565964+00:00 [queued]>
[2024-06-17T16:48:38.201-0400] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_data.extract_data manual__2024-06-17T20:48:32.565964+00:00 [queued]>
[2024-06-17T16:48:38.202-0400] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-17T16:48:38.219-0400] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2024-06-17 20:48:32.565964+00:00
[2024-06-17T16:48:38.228-0400] {standard_task_runner.py:63} INFO - Started process 273274 to run task
[2024-06-17T16:48:38.231-0400] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_data', 'extract_data', 'manual__2024-06-17T20:48:32.565964+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/spotify_data.py', '--cfg-path', '/tmp/tmphu2tpj2i']
[2024-06-17T16:48:38.237-0400] {standard_task_runner.py:91} INFO - Job 22: Subtask extract_data
[2024-06-17T16:48:38.273-0400] {task_command.py:426} INFO - Running <TaskInstance: spotify_data.extract_data manual__2024-06-17T20:48:32.565964+00:00 [running]> on host andres-IdeaPad-3-14ALC6
[2024-06-17T16:48:38.320-0400] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spotify_data' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T20:48:32.565964+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T20:48:32.565964+00:00'
[2024-06-17T16:48:38.321-0400] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T16:48:38.330-0400] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T16:48:38.331-0400] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/andres/Documentos/data_engineer/ETL-SPOTIPY/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andres/Documentos/data_engineer/ETL-SPOTIPY/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andres/Documentos/data_engineer/ETL-SPOTIPY/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andres/Documentos/data_engineer/ETL-SPOTIPY/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andres/Documentos/data_engineer/ETL-SPOTIPY/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andres/Documentos/data_engineer/ETL-SPOTIPY/airflow/dags/spotify_data.py", line 51, in extractData
    url = f"https://api.spotify.com/v1/me/player/recently-played?after={yesterday_unix_timestamp}"
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'yesterday_unix_timestamp' where it is not associated with a value
[2024-06-17T16:48:38.335-0400] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_data, task_id=extract_data, run_id=manual__2024-06-17T20:48:32.565964+00:00, execution_date=20240617T204832, start_date=20240617T204838, end_date=20240617T204838
[2024-06-17T16:48:38.343-0400] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task extract_data (cannot access local variable 'yesterday_unix_timestamp' where it is not associated with a value; 273274)
[2024-06-17T16:48:38.363-0400] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-17T16:48:38.377-0400] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-17T16:48:38.377-0400] {local_task_job_runner.py:222} INFO - ::endgroup::
